### PR TITLE
Remove broken link in README

### PR DESCRIPTION
**Pull request by kasium**

### CODE REVIEW

**Comment by maurerle** [comment]
Shouldn't we rather link to https://github.com/danjac/newsmeme and mention it as "newsmeme - a reddit clone written with flask and sqlalchemy" to get what this is about.
We can leave out the "Newsmeme" reference alltogether, but I like the example as itself somehow.

**Comment by kasium** [comment]
The repo is also archived. Maybe I can find an alternative to newsmeme

**Comment by kasium** [comment]
@maurerle what do you think about just coping the model from newsmeme, giving credits in a comment but to remove any other reference to it?

**Comment by maurerle** [comment]
yes sounds good

**Review by 12rambau — APPROVED** [review]

**Pull request closed without merging**
